train_data = {
    # English (50)
    "hello": "english",
    "hi": "english",
    "good morning": "english",
    "good night": "english",
    "how are you": "english",
    "thank you": "english",
    "see you later": "english",
    "nice to meet you": "english",
    "what is your name": "english",
    "where are you going": "english",
    "i am fine": "english",
    "good evening": "english",
    "have a nice day": "english",
    "take care": "english",
    "all the best": "english",
    "see you tomorrow": "english",
    "long time no see": "english",
    "good to see you": "english",
    "how is everything": "english",
    "where are you from": "english",
    "goodbye": "english",
    "i am good": "english",
    "what are you doing": "english",
    "have fun": "english",
    "hello!": "english",
    "hi!": "english",
    "good morning!": "english",
    "good night!": "english",
    "thank you!": "english",
    "see you later!": "english",
    "nice to meet you!": "english",
    "what is your name!": "english",
    "where are you going!": "english",
    "i am fine!": "english",
    "good evening!": "english",
    "have a nice day!": "english",
    "take care!": "english",
    "all the best!": "english",
    "see you tomorrow!": "english",
    "long time no see!": "english",
    "good to see you!": "english",
    "how is everything!": "english",
    "where are you from!": "english",
    "goodbye!": "english",
    "i am good!": "english",
    "what are you doing!": "english",
    "have fun!": "english",
    "you look very pale": "english",

    # Spanish (50)
    "hola": "spanish",
    "buenos dias": "spanish",
    "buenas noches": "spanish",
    "como estas": "spanish",
    "gracias": "spanish",
    "hasta luego": "spanish",
    "mucho gusto": "spanish",
    "cual es tu nombre": "spanish",
    "estoy bien": "spanish",
    "a donde vas": "spanish",
    "buenas tardes": "spanish",
    "que haces": "spanish",
    "como te llamas": "spanish",
    "cuidate": "spanish",
    "nos vemos mañana": "spanish",
    "adios": "spanish",
    "hasta pronto": "spanish",
    "que tal": "spanish",
    "disfruta": "spanish",
    "estoy cansado": "spanish",
    "me alegro de verte": "spanish",
    "buen viaje": "spanish",
    "feliz dia": "spanish",
    "hola!": "spanish",
    "buenos dias!": "spanish",
    "buenas noches!": "spanish",
    "como estas!": "spanish",
    "gracias!": "spanish",
    "hasta luego!": "spanish",
    "mucho gusto!": "spanish",
    "cual es tu nombre!": "spanish",
    "estoy bien!": "spanish",
    "a donde vas!": "spanish",
    "buenas tardes!": "spanish",
    "que haces!": "spanish",
    "como te llamas!": "spanish",
    "cuidate!": "spanish",
    "nos vemos mañana!": "spanish",
    "adios!": "spanish",
    "hasta pronto!": "spanish",
    "que tal!": "spanish",
    "disfruta!": "spanish",
    "estoy cansado!": "spanish",
    "me alegro de verte!": "spanish",
    "buen viaje!": "spanish",
    "feliz dia!": "spanish",

    # French (50)
    "bonjour": "french",
    "bonsoir": "french",
    "bonne nuit": "french",
    "comment ca va": "french",
    "merci": "french",
    "au revoir": "french",
    "enchanté de vous rencontrer": "french",
    "quel est ton nom": "french",
    "je vais bien": "french",
    "ou vas tu": "french",
    "salut": "french",
    "bonne soirée": "french",
    "tu t appelles comment": "french",
    "prends soin de toi": "french",
    "a bientot": "french",
    "bonne chance": "french",
    "comment tu vas": "french",
    "je suis fatigue": "french",
    "ravi de te voir": "french",
    "a demain": "french",
    "bon voyage": "french",
    "passe une bonne journée": "french",
    "je suis content": "french",
    "ca roule": "french",
    "bonjour!": "french",
    "bonsoir!": "french",
    "bonne nuit!": "french",
    "comment ca va!": "french",
    "merci!": "french",
    "au revoir!": "french",
    "enchanté de vous rencontrer!": "french",
    "quel est ton nom!": "french",
    "je vais bien!": "french",
    "ou vas tu!": "french",
    "salut!": "french",
    "bonne soirée!": "french",
    "tu t appelles comment!": "french",
    "prends soin de toi!": "french",
    "a bientot!": "french",
    "bonne chance!": "french",
    "comment tu vas!": "french",
    "je suis fatigue!": "french",
    "ravi de te voir!": "french",
    "a demain!": "french",
    "bon voyage!": "french",
    "passe une bonne journée!": "french",
    "je suis content!": "french",
    "ca roule!": "french",

    # German (50)
    "hallo": "german",
    "guten morgen": "german",
    "gute nacht": "german",
    "wie geht es dir": "german",
    "danke": "german",
    "auf wiedersehen": "german",
    "   ": "german",
    "wie heißt du": "german",
    "mir geht es gut": "german",
    "wo gehst du hin": "german",
    "servus": "german",
    "schönen abend": "german",
    "was machst du": "german",
    "pass auf dich auf": "german",
    "bis bald": "german",
    "tschüss": "german",
    "ich bin müde": "german",
    "viel glück": "german",
    "freut mich dich zu sehen": "german",
    "bis morgen": "german",
    "gute reise": "german",
    "schönen tag noch": "german",
    "alles gute": "german",
    "ich freue mich": "german",
    "hallo!": "german",
    "guten morgen!": "german",
    "gute nacht!": "german",
    "wie geht es dir!": "german",
    "danke!": "german",
    "auf wiedersehen!": "german",
    "schön dich zu treffen!": "german",
    "wie heißt du!": "german",
    "mir geht es gut!": "german",
    "wo gehst du hin!": "german",
    "servus!": "german",
    "schönen abend!": "german",
    "was machst du!": "german",
    "pass auf dich auf!": "german",
    "bis bald!": "german",
    "tschüss!": "german",
    "ich bin müde!": "german",
    "viel glück!": "german",
    "freut mich dich zu sehen!": "german",
    "bis morgen!": "german",
    "gute reise!": "german",
    "schönen tag noch!": "german",
    "alles gute!": "german",
    "ich freue mich!": "german",
}

test_data = {
    # English
    "how is everything": "english",
    "good evening": "english",
    "what are you doing": "english",
    "see you tomorrow": "english",
    "good to see you": "english",
    "long time no see": "english",
    "i am fine": "english",
    "where are you from": "english",
    "all the best": "english",
    "have fun": "english",

    # Spanish
    "nos vemos mañana": "spanish",
    "adios": "spanish",
    "hasta pronto": "spanish",
    "que tal": "spanish",
    "disfruta": "spanish",
    "estoy cansado": "spanish",
    "me alegro de verte": "spanish",
    "buen viaje": "spanish",
    "feliz dia": "spanish",
    "como te llamas": "spanish",

    # French
    "a bientot": "french",
    "bonne chance": "french",
    "comment tu vas": "french",
    "je suis fatigue": "french",
    "ravi de te voir": "french",
    "a demain": "french",
    "bon voyage": "french",
    "passe une bonne journée": "french",
    "je suis content": "french",
    "ca roule": "french",

    # German
    "bis bald": "german",
    "tschüss": "german",
    "ich bin müde": "german",
    "viel glück": "german",
    "freut mich dich zu sehen": "german",
    "bis morgen": "german",
    "gute reise": "german",
    "schönen tag noch": "german",
    "alles gute": "german",
    "ich freue mich": "german",
}
